# Generated by Django 5.1 on 2024-09-12 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_workoutcomment_delete_workoutcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='workout_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
