# Generated by Django 5.1 on 2024-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_workout_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingset',
            name='type',
            field=models.CharField(choices=[('warmup', 'Warm Up set'), ('working', 'Working set'), ('dropset', 'Drop set'), ('restpause', 'Rest pause set'), ('myo', 'Myo set'), ('cluster', 'Cluster set'), ('super', 'Super set')], default='working', max_length=10),
        ),
    ]
