# Generated by Django 5.1 on 2024-12-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutcomment",
            name="content",
            field=models.TextField(max_length=300),
        ),
    ]
