# Generated by Django 5.1 on 2025-03-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0002_alter_workoutcomment_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workingset",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="workingset",
            name="workout",
        ),
        migrations.AddField(
            model_name="workingset",
            name="workout_exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workingsets",
                to="fitness.workoutexercise",
            ),
            preserve_default=False,
        ),
    ]
