name: Linting & Code Quality
run-name: Repository code is being linted and quality is verified

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run Flake8 (Python Linter)
        run: flake8 . --count --show-source --statistics --exclude=migrations,*migrations*,settings.py

      - name: Run Black (Code Formatter)
        run: black --check --line-length 79 .
